### PR TITLE
Improve ElementType ergonomics

### PR DESCRIPTION
**Pull request by pnehrer**
Minor improvements to ElementType ergonomics:

- derive Copy, Clone to make it easier to pass around as a type vs. u32
- derive PartialEq, Eq to make instances comparable
- implement TryFrom<u32> with a custom error
- implement conversion Into u32
- implement Display

If you accept, I have a follow-up PR that would change some of the u32 return values to ElementType in Node and Tensor, but this would be a breaking change.

### CODE REVIEW

**Comment by abrown** [comment]
@pnehrer, thanks again for the contribution! I'm going to merge #99 first since that was sitting in the queue and that might cause you a bit of rebasing headache &mdash; hopefully not too much. And feel free to replace those `u32`s with `ElementType` since we haven't yet published a version that contains these new 2.0 changes.

**Comment by pnehrer** [comment]
@abrown I resolved the merge conflict and this is now ready to go

**Review by abrown — APPROVED** [review]
Makes sense to me &mdash; thanks!

**Comment by pnehrer** [comment]
Thank you again!

**Pull request merged**
